development:
  :client_id: '3MVG9QDx8IX8nP5RUXIFbi3L4rSVruiBU4O_ozvkJiU0aGZDBxfsF6XDhngJf6Ha2fDNniyDxpt0Gb9Pp.2Tk'
  :client_secret: '7712607496533706277'
  :username: 'dfriedman@dforce.com'
  :password: 'Mavens123'
  :api_version: '27.0'
test:
  :client_id: '3MVG9QDx8IX8nP5RUXIFbi3L4rSVruiBU4O_ozvkJiU0aGZDBxfsF6XDhngJf6Ha2fDNniyDxpt0Gb9Pp.2Tk'
  :client_secret: '7712607496533706277'
  :username: 'dfriedman@dforce.com'
  :password: 'Mavens123'
  :api_version: '27.0'